export const CAKES = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    price: 150000,
    description:
      "Apple's latest flagship with an A17 Pro chip, titanium build, and a triple camera setup for stunning photography.",
    imageUrl: "https://m.media-amazon.com/images/I/81dT7CUY6GL._SL1500_.jpg",
    storage: "1TB",
    ingredients: ["A17 Pro Chip", "8GB RAM", "4323mAh Battery", "48MP Camera", "6.7-inch Display"],
    category: "Flagship Phones",
    available: true,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Samsung Galaxy S23",
    price: 70000,
    description:
      "A flagship phone with a sleek design, Snapdragon 8 Gen 2, and a 50MP main camera, delivering outstanding performance and photography.",
    imageUrl: "https://m.media-amazon.com/images/I/71RnJXDexML._SL1500_.jpg",
    storage: "128GB",
    ingredients: ["Snapdragon 8 Gen 2", "8GB RAM", "3900mAh Battery", "50MP Camera", "6.1-inch Dynamic AMOLED Display"],
    category: "Flagship Phones",
    available: true,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Google Pixel 8 Pro",
    price: 105000,
    description:
      "Google's flagship featuring Tensor G3, incredible AI-powered cameras, and a stunning 6.7-inch LTPO OLED display.",
    imageUrl: "https://www.designinfo.in/wp-content/uploads/2023/10/Google-Pixel-8-Pro-Black-1-485x485-optimized.webp",
    storage: "256GB",
    ingredients: ["Tensor G3", "12GB RAM", "5050mAh Battery", "50MP Camera", "6.7-inch Display"],
    category: "Flagship Phones",
    available: true,
    rating: 4.8,
  },
  {
    id: 4,
    name: "OnePlus 12",
    price: 70000,
    description:
      "A premium smartphone with a Snapdragon 8 Gen 3 processor, sleek design, and fast charging capabilities.",
    imageUrl: "https://m.media-amazon.com/images/I/71YzJwmRFCL._SL1500_.jpg",
    storage: "512GB",
    ingredients: ["Snapdragon 8 Gen 3", "16GB RAM", "5000mAh Battery", "50MP Camera", "6.7-inch AMOLED Display"],
    category: "Flagship Phones",
    available: true,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Xiaomi 13 Ultra",
    price: 85000,
    description:
      "A powerhouse with Leica-tuned cameras, Snapdragon 8 Gen 2, and a 120Hz AMOLED display.",
    imageUrl: "https://m.media-amazon.com/images/I/71MsYJjQhBL._SL1500_.jpg",
    storage: "1TB",
    ingredients: ["Snapdragon 8 Gen 2", "16GB RAM", "5000mAh Battery", "50MP Camera", "6.73-inch AMOLED Display"],
    category: "Premium Phones",
    available: true,
    rating: 4.9,
  },
  {
    id: 6,
    name: "Realme GT 5",
    price: 45000,
    description:
      "A budget-friendly flagship killer with Snapdragon 8 Gen 2, super-fast charging, and a 144Hz OLED display.",
    imageUrl: "https://m.media-amazon.com/images/I/71OoxNHXPoL._SL1500_.jpg",
    storage: "256GB",
    ingredients: ["Snapdragon 8 Gen 2", "12GB RAM", "4600mAh Battery", "50MP Camera", "6.74-inch AMOLED Display"],
    category: "Budget Phones",
    available: true,
    rating: 4.8,
  },
  {
    id: 7,
    name: "Moto G Power",
    price: 14999,
    description:
      "The Moto G Power is a budget-friendly smartphone with long-lasting battery life and a 48MP triple camera setup.",
    imageUrl: "https://m.media-amazon.com/images/I/71zoUhd6fXL._SL1500_.jpg",
    storage: "64GB",
    ingredients: ["Snapdragon 662", "4GB RAM", "5000mAh Battery", "48MP Camera", "6.6-inch Full HD Display"],
    category: "Budget Phones",
    available: true,
    rating: 4.3,
  },
  {
    id: 8,
    name: "Redmi Note 12",
    price: 17999,
    description:
      "The Redmi Note 12 comes with a 48MP camera, large battery, and a 90Hz AMOLED display for a smooth experience at an affordable price.",
    imageUrl: "https://m.media-amazon.com/images/I/81MZRUuHJIL._SL1500_.jpg",
    storage: "64GB",
    ingredients: ["Snapdragon 4 Gen 1", "4GB RAM", "5000mAh Battery", "48MP Camera", "6.67-inch AMOLED Display"],
    category: "Budget Phones",
    available: true,
    rating: 4.4,
  },
  {
    id: 9,
    name: "iQOO 12 5G",
    price: 64999,  
    description:
      "The iQOO 12 5G is powered by Snapdragon 8 Gen 3, a vibrant 120Hz AMOLED display, and a 50MP camera with advanced photography features.",
    imageUrl: "https://m.media-amazon.com/images/I/61B32CL2BCL._SL1200_.jpg", 
    storage: "256GB",
    ingredients: ["Snapdragon 8 Gen 3", "12GB RAM", "5000mAh Battery", "50MP Camera", "6.78-inch 120Hz AMOLED Display"],
    category: "5G Phones",
    available: true,
    rating: 4.8,
},
{
  id: 10,
  name: "OnePlus 11 5G",
  price: 54999,
  description:
    "OnePlus 11 5G is powered by Snapdragon 8 Gen 2, 120Hz Fluid AMOLED display, and a powerful 50MP Hasselblad camera for an amazing experience.",
  imageUrl: "https://m.media-amazon.com/images/I/61amb0CfMGL._SL1500_.jpg",
  storage: "256GB",
  ingredients: ["Snapdragon 8 Gen 2", "12GB RAM", "5000mAh Battery", "50MP Hasselblad Camera", "6.7-inch 120Hz Fluid AMOLED Display"],
  category: "Flagship Phones",
  available: true,
  rating: 4.7,
},
{
  id: 11,
  name: "Xiaomi 13 Pro",
  price: 74999,
  description:
    "Xiaomi 13 Pro features the powerful Snapdragon 8 Gen 2, Leica optics for amazing photos, and a beautiful 120Hz AMOLED display.",
  imageUrl: "https://m.media-amazon.com/images/I/61RvCwjI7dL._SL1500_.jpg",
  storage: "256GB",
  ingredients: ["Snapdragon 8 Gen 2", "12GB RAM", "4820mAh Battery", "50MP Leica Camera", "6.73-inch 120Hz AMOLED Display"],
  category: "Camera Phones",
  available: true,
  rating: 4.8,
},
{
  id: 12,
  name: "Vivo Y300 Plus",
    price: 15999,
    description:
      "Vivo Y300 Plus offers an impressive 50MP AI camera, a large 5000mAh battery, and a smooth 90Hz display for a great value in the budget segment.",
    imageUrl: "https://m.media-amazon.com/images/I/61Vv9HSxhGL._SL1200_.jpg",
    storage: "128GB",
    ingredients: ["MediaTek Dimensity 700", "6GB RAM", "5000mAh Battery", "50MP AI Camera", "6.58-inch 90Hz Display"],
    category: "Budget Phones",
    available: true,
    rating: 4.4,
},


];